default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: atmosfeel
  password: passer@X86
  host: 10.0.2.15

development:
  <<: *default
  database: sample_rails_app_development

test:
  <<: *default
  database: sample_rails_app_test

production:
  <<: *default
  database: sample_rails_app_production
